"""make_payment_reservation_id_nullable

Revision ID: c20eed016def
Revises: 3b3dc65cb4b1
Create Date: 2025-11-26 01:35:32.806356
"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'c20eed016def'
down_revision = '3b3dc65cb4b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('password_reset_tokens_token_key', 'password_reset_tokens', type_='unique')
    op.drop_index('ix_password_reset_tokens_token', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.alter_column('payments', 'reservation_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # Check if constraint exists before dropping
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = [c['name'] for c in inspector.get_unique_constraints('payments')]
    if 'payments_reservation_id_key' in constraints:
        op.drop_constraint('payments_reservation_id_key', 'payments', type_='unique')
    op.alter_column('reservations', 'amount_minor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'baggage_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('settlements', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('settlements', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('settlements', 'commission_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('settlements_payment_id_key', 'settlements', type_='unique')
    op.drop_index('ix_settlements_payment_id', table_name='settlements')
    op.create_index(op.f('ix_settlements_payment_id'), 'settlements', ['payment_id'], unique=True)
    op.alter_column('staff', 'assigned_location_ids',
               existing_type=sa.VARCHAR(length=512),
               comment='Comma-separated location IDs',
               existing_nullable=True)
    op.alter_column('staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('staff_user_id_key', 'staff', type_='unique')
    op.drop_index('ix_staff_user_id', table_name='staff')
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=True)
    op.drop_index('ix_lockers_location_id', table_name='storages')
    op.drop_index('ix_lockers_tenant_id', table_name='storages')
    op.create_index(op.f('ix_storages_location_id'), 'storages', ['location_id'], unique=False)
    op.create_index(op.f('ix_storages_tenant_id'), 'storages', ['tenant_id'], unique=False)
    op.drop_column('tenant_plan_limits', 'max_storages')
    op.alter_column('tenants', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('webhook_deliveries', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('webhook_deliveries', 'tenant_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'target_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'request_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'signature',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('webhook_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.alter_column('widget_configs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('widget_configs_id_seq'::regclass)"))
    op.alter_column('widget_configs', 'tenant_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('widget_configs', 'widget_public_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('widget_configs', 'widget_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('widget_configs', 'allowed_origins',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('widget_configs', 'locale',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('widget_configs', 'theme',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('widget_configs', 'form_defaults',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('widget_configs', 'notification_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('widget_configs', 'webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('widget_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index('idx_widget_configs_tenant', table_name='widget_configs')
    op.drop_constraint('widget_configs_tenant_id_widget_public_key_key', 'widget_configs', type_='unique')
    op.create_foreign_key(None, 'widget_configs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('widget_reservations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('widget_reservations', 'tenant_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'config_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('widget_reservations', 'external_ref',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'source',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'locker_size',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'guest_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'guest_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'guest_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'kvkk_approved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('widget_reservations', 'origin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index('idx_widget_reservations_tenant', table_name='widget_reservations')
    op.create_index(op.f('ix_widget_reservations_tenant_id'), 'widget_reservations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'widget_reservations', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widget_reservations', type_='foreignkey')
    op.drop_index(op.f('ix_widget_reservations_tenant_id'), table_name='widget_reservations')
    op.create_index('idx_widget_reservations_tenant', 'widget_reservations', ['tenant_id'], unique=False)
    op.alter_column('widget_reservations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('widget_reservations', 'user_agent',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'origin',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'kvkk_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'guest_phone',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'guest_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'guest_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'locker_size',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'source',
               existing_type=sa.String(length=32),
               server_default=sa.text("'widget'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'status',
               existing_type=sa.String(length=32),
               server_default=sa.text("'pending'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'external_ref',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_reservations', 'config_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('widget_reservations', 'tenant_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('widget_reservations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'widget_configs', type_='foreignkey')
    op.create_unique_constraint('widget_configs_tenant_id_widget_public_key_key', 'widget_configs', ['tenant_id', 'widget_public_key'])
    op.create_index('idx_widget_configs_tenant', 'widget_configs', ['tenant_id'], unique=False)
    op.alter_column('widget_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('widget_configs', 'webhook_url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('widget_configs', 'notification_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('widget_configs', 'form_defaults',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('widget_configs', 'theme',
               existing_type=sa.String(length=16),
               server_default=sa.text("'light'::text"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('widget_configs', 'locale',
               existing_type=sa.String(length=16),
               server_default=sa.text("'tr-TR'::text"),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('widget_configs', 'allowed_origins',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('widget_configs', 'widget_secret',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('widget_configs', 'widget_public_key',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('widget_configs', 'tenant_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('widget_configs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('widget_configs_id_seq'::regclass)"))
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.alter_column('webhook_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('webhook_deliveries', 'signature',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('webhook_deliveries', 'request_body',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'target_url',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'event_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'tenant_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tenants', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('tenant_plan_limits', sa.Column('max_storages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_storages_tenant_id'), table_name='storages')
    op.drop_index(op.f('ix_storages_location_id'), table_name='storages')
    op.create_index('ix_lockers_tenant_id', 'storages', ['tenant_id'], unique=False)
    op.create_index('ix_lockers_location_id', 'storages', ['location_id'], unique=False)
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.create_index('ix_staff_user_id', 'staff', ['user_id'], unique=False)
    op.create_unique_constraint('staff_user_id_key', 'staff', ['user_id'])
    op.alter_column('staff', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('staff', 'assigned_location_ids',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='Comma-separated location IDs',
               existing_nullable=True)
    op.drop_index(op.f('ix_settlements_payment_id'), table_name='settlements')
    op.create_index('ix_settlements_payment_id', 'settlements', ['payment_id'], unique=False)
    op.create_unique_constraint('settlements_payment_id_key', 'settlements', ['payment_id'])
    op.alter_column('settlements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('settlements', 'commission_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'5'::double precision"),
               existing_nullable=False)
    op.alter_column('settlements', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('settlements', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'TRY'::character varying"),
               existing_nullable=False)
    op.alter_column('reservations', 'baggage_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('reservations', 'amount_minor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('payments_reservation_id_key', 'payments', ['reservation_id'])
    op.alter_column('payments', 'reservation_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_unique_constraint('password_reset_tokens_token_key', 'password_reset_tokens', ['token'])
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("timezone('utc'::text, now())"),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
